USE [01_ACRD]
GO

IF (OBJECT_ID('DBO.[TB_PRODUCT]') IS NOT NULL) DROP TABLE DBO.[TB_PRODUCT]
GO

CREATE TABLE [dbo].[TB_PRODUCT]
(
  [ID_PRODUCT] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [DT_CREATED_ON] DATETIME NULL,
  [FL_ACTIVE] BIT NULL,
  [FL_REMOVED] BIT NULL,

  [DS_NAME] VARCHAR(250) NULL,
  [DS_DESCRIPTION] VARCHAR(500) NULL,
  [VL_UNIT_PRICE] DECIMAL NULL,
  [NR_QUANTITY] INT NULL,
  [NR_TYPE] INT NULL,

  [ID_CATEGORY] INT NOT NULL,

  CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (ID_CATEGORY) REFERENCES TB_CATEGORY(ID_CATEGORY)
);