USE [01_ACRD]
GO

IF (OBJECT_ID('DBO.TB_CATEGORY') IS NOT NULL) DROP TABLE DBO.TB_CATEGORY
GO

CREATE TABLE [dbo].[TB_CATEGORY]
(
  [ID_CATEGORY] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [DT_CREATED_ON] DATETIME NULL,
  [FL_ACTIVE] BIT NULL,
  [FL_REMOVED] BIT NULL,

  [DS_NAME] VARCHAR(200) NULL,
  [DS_DESCRIPTION] VARCHAR(1000) NULL
);